# Generated by Django 3.1.2 on 2020-12-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201216_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
