# Generated by Django 3.1.2 on 2020-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_mgr', '0003_strategyserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyserver',
            name='stg_server_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
