# Generated by Django 3.1.2 on 2020-12-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_mgr', '0005_strategyserver_stg_server_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyserver',
            name='stg_server_owner',
            field=models.CharField(max_length=128),
        ),
    ]
