# Generated by Django 3.1.2 on 2020-12-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_mgr', '0006_auto_20201221_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='stg_file_path',
            field=models.FileField(upload_to='./strategy/'),
        ),
    ]
