# Generated by Django 3.1.2 on 2020-12-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stg_name', models.CharField(max_length=30, unique=True)),
                ('stg_owner', models.CharField(max_length=128)),
                ('stg_description', models.CharField(max_length=512)),
                ('stg_create_time', models.DateTimeField(auto_now_add=True)),
                ('stg_modify_time', models.DateTimeField(auto_now=True)),
                ('stg_file_path', models.FileField(upload_to='./')),
            ],
        ),
    ]
