# Generated by Django 3.1.2 on 2020-12-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting_mgr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
