# Generated by Django 3.1.2 on 2020-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting_mgr', '0002_delete_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_owner', models.CharField(max_length=128)),
                ('task_strategy_list', models.CharField(max_length=10000)),
                ('task_dataset_list', models.CharField(max_length=10000)),
                ('task_policy', models.IntegerField()),
                ('task_status', models.BooleanField()),
                ('task_result', models.CharField(max_length=100000)),
                ('task_create_time', models.DateTimeField(auto_now_add=True)),
                ('task_modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('task_name', 'task_owner')},
            },
        ),
    ]
