# Generated by Django 3.1.2 on 2020-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='data_frequency',
            field=models.CharField(max_length=30),
        ),
    ]
