# Generated by Django 3.1.2 on 2020-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mgr', '0003_auto_20201222_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histdata',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
